on:
  schedule:
    - cron: "0 11 * * *" # every 24 hours
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name 'Djordje Ljubinkovic'
          git config user.email 'ljubinkovicdj93@gmail.com'
          git add *.md
          git commit -m "Update README.md"
          git push
        fi
